language: node_js
node_js:
- '5'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- npm install phantomjs-prebuilt
install:
- npm install
- bower install
script:
- ember test
deploy:
  provider: heroku
  api_key:
    secure: DrI1YwLCQBLHzOa31o/cX44EB8E1sJ2ilI+zBEitHBFwz5UDhKhc+HDgiNfq+W7wXDFqWUnhGs6fUOqCI37rnTpAKnPt8X7hoQZ5NCn65CWZ9F1K2elVKdoi+x8FiKKuDL6wO8ZI+er1Q7JNfSlx0hKlgRv6eDMnLez0EOyy+dWlRoQ/aprNiawu9UR1qZnkwLgfqwUR1Y0HD77BcDb38YSmfjG11/OLXu6qkgWZOOtwN2r7ToRHq2DK3sngBncYlh3OhvMnORKBkYA+K+93pBH+T5NJ8FYs3U46zFB+ewfPzpWSK/vKklPcPFIC8IBcWl91ApUIrGWZnGUEw70mlRah+EcErI0IMG54cRgJ7LwTQLogXLiu7cAr33IE9yCTpo8+iJbm+vQ2bNp4hmBreJ053qakcSgoI9OTCVuYcIodobOMFPLmrvFjZE21so8xAujc291WNQ58dTvzZpjaZECmjnUz9zS61DXS6GpCFIsVkWaqd8TezUlokApuSiQx6uJuapzgAnczCDu2ySrnSWSTRTwwxM61kV8HdIGohCsCce+KXf2UiYjNE6ZwuCOpLQQTox5clmZbaK4h5860UX6uyYOAZYD1pQC4Z5OkzZ89HSsIINmb9bI6LRQ7vuCKX/brxqasjDZBo2hVJvQoSMvR8XCv4xYGBVAEjd9seqA=
  app: fastboot-website
  on:
    repo: ember-fastboot/fastboot-website
